# -*- coding: utf-8 -*-
"""Python_function_assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mFzj6KWyDvPzvLzT7kLsXTx515ZQC_ob

# Python_function_assignment
1. What is the difference between a function and a method in Python?

   ans -
   
   method

- Method is called by its name, but it is associated to an object (dependent).
   
- A method definition always includes 'self' as its first parameter.

- A method is implicitly passed to the object on which it is invoked.

- It may or may not return any data.

  function

- Function is block of code that is also called by its name.
  
- The function can have different parameters or may not have any at all.

- If any data (parameters) are passed, they are passed explicitly.

- It may or may not return any data.

- Function does not deal with Class and its instance concept.

2.Explain the concept of function arguments and parameters in Python.

ans

  - Parameters are variables defined in a function declaration. This act as placeholders for the values (arguments) that will be passed to the function.

 - Arguments are the actual values that you pass to the function when you call it. These values replace the parameters defined in the function.

 3.What are the different ways to define and call a function in Python?

 ans

 By using the word def keyword followed by the function's name and parentheses () we can define a function.

 Defining a function

def fun():

To call a function in Python, we definitely type the name of the function observed via parentheses ().

Calling a function:

function_name(arguments)

4. What is the purpose of the `return` statement in a Python function?

ans-

The return statement is used inside a function to send a value back to the place where the function was called.

5. What are iterators in Python and how do they differ from iterables?

ans-

An iterator is an object, which is used to iterate over an iterable object using the __next__() method. Iterators have the __next__() method, which returns the next item of the object.

iterable is an object, that one can iterate over. It generates an Iterator when passed to iter() method.

6. Explain the concept of generators in Python and how they are defined.

ans

 generator function is a special type of function that returns an iterator object. Instead of using return to send back a single value, generator functions use yield to produce a series of results over time.

 def fun():
    yield 1            
    yield 2            
    yield 3

7. What are the advantages of using generators over regular functions?

ans

Memory Efficiency:

One of the biggest advantages of generators is that they are memory efficient. Since a generator yields its values one by one, it does not need to store all of the values in memory at once.

Readability:

Generators can make your code easier to read and understand. By breaking up the iteration process into smaller chunks, you can write code that is more concise and easier to follow.

Speed:

Generators can also be faster than regular loops, especially when working with large data sets.

8. What is a lambda function in Python and when is it typically used?

ans

Lambda functions are small anonymous functions, meaning they do not have a defined name. These are small, short-lived functions used to pass simple logic to another function.

a = 'nadeemshekh'
upper = lambda x: x.upper()  
print(upper(a))                          
output- NADEEMSHEKH

9. Explain the purpose and usage of the `map()` function in Python.

Ans-

map() function in Python applies a given function to each element of an iterable (list, tuple, set, etc.) and returns a map object (iterator). It is a higher-order function used for uniform element-wise transformations, enabling concise and efficient code.

example-

s = ['1', '2', '3', '4']

res = map(int, s)

print(list(res))

9. What is the difference between `map()`, `reduce()`, and `filter()` functions in Python?

ans-

Map Function in Python

map() function returns a map object(which is an iterator) of the results after applying the given function to each item of a given iterable list, tuple etc.

Reduce Function in Python

The reduce function is used to apply a particular function passed in its argument to all of the list elements mentioned in the sequence passed along.This function is defined in "functools" module.

Filter Function in Python

The filter() method filters the given sequence with the help of a function that tests each element in the sequence to be true or not.

11. Using pen & Paper write the internal mechanism for sum operation using  reduce function on this given
list:[47,11,42,13];

ans-
"""

from functools import reduce
a = [47,11,42,13]
r = reduce(lambda x, y: x + y, a)
print(r)

# Practical Questions:
# 1. Write a Python function that takes a list of numbers as input and returns the sum of all even numbers in
# the list.

# ans-
def even_sum(NumList):
    Even_Sum = 0
    for j in range(Number):
        if(NumList[j] % 2 == 0):
            Even_Sum = Even_Sum + NumList[j]
    return Even_Sum
    NumList = []
Number = int(input("Please enter the Total Number of List Elements: "))
for i in range(1, Number + 1):
    value = int(input("Please enter the Value of %d Element : " %i))
    NumList.append(value)
Even_Sum = even_sum(NumList)
print("\nThe Sum of Even Numbers in this List =  ", Even_Sum)

# 2.Create a Python function that accepts a string and returns the reverse of that string.

# ans
def reverse(s):
    str = ""
    for i in s:
        str = i + str
    return str

# 3. Implement a Python function that takes a list of integers and returns a new list containing the squares of
# each number.
# ans-
def square_numbers(input_list):
    squared_list = []
    for number in input_list:
        squared_list.append(number ** 2)
    return squared_list

# Demonstration
numbers = [1, 2, 3, 4, 5]
result = square_numbers(numbers)
print(f"Original list: {numbers}")
print(f"Squared list: {result}")

# 4. Write a Python function that checks if a given number is prime or not from 1 to 200.
# Ans

def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

print("Prime numbers from 1 to 200:")
for number in range(1, 201):
    if is_prime(number):
        print(f"{number} is a prime number")
    else:
        print(f"{number} is not a prime number")


# 5. Create an iterator class in Python that generates the Fibonacci sequence up to a specified number of
# terms.
# ans

class FibonacciIterator:
    def __init__(self, n_terms):
        self.n_terms = n_terms
        self.current_term = 0
        self.a = 0
        self.b = 1

    def __iter__(self):
        return self

    def __next__ (self):
        if self.current_term < self.n_terms:
            if self.current_term == 0:
                self.current_term += 1
                return self.a
            elif self.current_term == 1:
                self.current_term += 1
                return self.b
            else:
                next_fib = self.a + self.b
                self.a = self.b
                self.b = next_fib
                self.current_term += 1
                return next_fib
        else:
            raise StopIteration

# Demonstration of the FibonacciIterator
print("Fibonacci sequence for 10 terms:")
fib_seq = FibonacciIterator(10)
for num in fib_seq:
    print(num)
# 6. Write a generator function in Python that yields the powers of 2 up to a given exponent.
# ans
def powers_of_two(exponent):
    for i in range(exponent + 1):
        yield 2 ** i

# Demonstration
print("Powers of 2 up to exponent 5:")
for power in powers_of_two(5):
    print(power)

# 7. Implement a generator function that reads a file line by line and yields each line as a string.
# ans

def read_file_lines(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            yield line

# 8. Use a lambda function in Python to sort a list of tuples based on the second element of each tuple.
# ans
data = [('apple', 3), ('banana', 1), ('cherry', 2), ('date', 4)]
sorted_data = sorted(data, key=lambda x: x[1])
print("Original list:", data)
print("Sorted list (by second element):", sorted_data)

# 9. Write a Python program that uses `map()` to convert a list of temperatures from Celsius to Fahrenheit.
# ans

def celsius_to_fahrenheit(celsius):
    return (celsius * 9/5) + 32

celsius_temperatures = [0, 10, 20, 30, 40]
fahrenheit_temperatures = list(map(celsius_to_fahrenheit, celsius_temperatures))
print("Celsius Temperatures:", celsius_temperatures)
print("Fahrenheit Temperatures:", fahrenheit_temperatures)

# 10. Create a Python program that uses `filter()` to remove all the vowels from a given string
# ans
def remove_vowels(input_string):
    vowels = 'aeiouAEIOU'
    filtered_chars = filter(lambda char: char not in vowels, input_string)
    return ''.join(filtered_chars)

# Demonstration
my_string = "Hello World! This is a test string."
string_without_vowels = remove_vowels(my_string)
print(f"Original string: {my_string}")
print(f"String without vowels: {string_without_vowels}")